export const DEFAULTS = {
  MAX_AGENTS_PER_COMPANY: 20,
  MAX_HIRE_DEPTH: 3,
  AGENT_JWT_TTL_SECONDS: 172800, // 48h
  FLY_REGION: 'sjc',
  FLY_VM_SIZE: 'shared-cpu-2x',
  FLY_IDLE_TIMEOUT_MIN: 10,
  EXECUTOR_PORT: 3200,
  BACKEND_PORT: 3100,
} as const;
